import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Word File',
  description: 'Generated by me',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang='ru'>
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
